language: java

dist: xenial

jdk:
  - openjdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script: ./travis_build.sh

#deploy:
#  - provider: script
#    skip_cleanup: true
#    script: ./gradlew publishPlugin -Pgradle.publish.key=${GRADLE_PUBLISH_KEY} -Pgradle.publish.secret=${GRADLE_PUBLISH_SECRET} -Dorg.gradle.project.version=${TRAVIS_TAG}
#    on:
#      tags: true
#      repo: ${TRAVIS_REPO_SLUG}

