name: 'publish'

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '24'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Retrieve tag name
        uses: little-core-labs/get-git-tag@v3.0.2
        id: tagName
        with:
          tagRegex: "v(.*)"

      - name: Publish plugins
        run: |
          ./gradlew publishPlugins \
            -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} \
            -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }} \
            -Pversion=${{ steps.tagName.outputs.tag }}
