name: 'publish'
on:
  push:
    tags:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Retrieve tag name
        uses: olegtarasov/get-tag@v2
        id: tagName
        with:
          tagRegex: "v(.*)"
      - name: gradle publishPlugins
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: publishPlugins -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }} -Pversion=${{ env.GIT_TAG_NAME }}
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
