name: 'test-only'

on:
  push:
    paths-ignore:
      - README.adoc
      - .gitignore
      - .editorconfig
      - LICENSE.txt
      - LICENSE
    branches:
      - main
  pull_request:
    paths-ignore:
      - README.adoc
      - .gitignore
      - .editorconfig
      - LICENSE.txt
      - LICENSE

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '24'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Check
        run: ./gradlew check
