name: 'test-only'

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: gradle check
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: check
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
