name: 'test-only'

on:
  push:
    paths-ignore:
      - README.adoc
      - .gitignore
      - .editorconfig
      - LICENSE.txt
      - LICENSE
    branches:
      - main
  pull_request:
    paths-ignore:
      - README.adoc
      - .gitignore
      - .editorconfig
      - LICENSE.txt
      - LICENSE

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Check
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check
          # Disable cache because of corruption
          cache-disabled: true
