name: 'test-only'

on:
  push:
    paths-ignore:
      - README.adoc
      - .gitignore
      - .editorconfig
      - LICENSE.txt
      - LICENSE
    branches:
      - master
  pull_request:
    paths-ignore:
      - README.adoc
      - .gitignore
      - .editorconfig
      - LICENSE.txt
      - LICENSE

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 8
      - name: gradle check
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check
          # Disable cache because of corruption
          cache-disabled: true
